[template]
# 直接在当前目录生成而不是创建一个新的子文件夹（true）
init = false
exclude = ["cliff.toml"]
#ignore = ["cliff.toml"]

[placeholders]
# 作者姓名（默认值 + 提示， git 配置文件中读取）
#author = { type = "string", prompt = "author name", default = "gatspy" }

# 作者邮箱（默认值，不提示 git 配置文件中读取）
#email = { type = "string", prompt = "email", default = "gatspy.if@gmail.com" }

# GitHub 用户名（强制用户输入）
github-username = { type = "string", prompt = "GitHub username", required = false, default = "gatspy" }

# 项目名称（project-name 内置占位符）